### ISSUE TITLE
bad values do not seem to return null

### ISSUE THREAD

**Issue by jefferis** [bocklab/transform_service#1]
Against [this endpoint](https://spine.janelia.org/app/transform-service/docs#/transform/transform_values_array_transform_dataset__dataset__s__scale__values_array_post), I used to get NaNs when submitting bad values. The docs say 

> Error values are returned as null, not NaN as done with the previous iteration of this service. The most likely cause of an error is being out-of-bounds of the underlying array.

But Instead when I do this:
```
curl -X POST "https://spine.janelia.org/app/transform-service/transform/dataset/flywire_v1/s/2/values_array" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"x\":[119260,119260],\"y\":[71134,71134],\"z\":[-2267,2267]}"
```
I get this:

```
Response bodyDownload{   "x": [     -2305843009213694000,     119627   ],   "y": [     -2305843009213694000,     70925   ],   "z": [     -2267,     2267   ],   "dx": [     -2305843009213694000,     367   ],   "dy": [     -2305843009213694000,     -209   ] }

```
Could you advise @perlman? Thanks!

**Comment by perlman** [comment]
I have identified the issue and will fix it shortly.

I made some tweaks to read the field values as uint64 instead of float to handle segmentation IDs > 2^53. In a failed effort to be clever, I reused the field type, but that's uint16, not float.

**Comment by perlman** [comment]
Fixed in https://github.com/bocklab/transform_service/commit/f40d1e72d245f3d447ceb0992082107e154cbb58.

```
curl -X POST "https://spine.janelia.org/app/transform-service/transform/dataset/flywire_v1/s/2/values_array" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"x\":[119260,119260],\"y\":[71134,71134],\"z\":[-2267,2267]}"
```

```
{"x":[null,119627.0],"y":[null,70925.0],"z":[-2267.0,2267.0],"dx":[null,367.0],"dy":[null,-209.0]}
```
